"""changed sportparticipant model, added columns

Revision ID: 29d28810b02b
Revises: c1f003acf586
Create Date: 2023-04-13 22:40:25.016555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d28810b02b'
down_revision = 'c1f003acf586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identity', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('active_subscriptions', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_column('active_subscriptions')
        batch_op.drop_column('identity')

    # ### end Alembic commands ###
