"""created onetimepayment model

Revision ID: 36e3b3ed9ac0
Revises: 8467f59cfc3e
Create Date: 2023-04-16 15:47:54.179152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e3b3ed9ac0'
down_revision = '8467f59cfc3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one_time_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paid_by', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('one_time_payments')
    # ### end Alembic commands ###
