"""many to many sport&participant

Revision ID: 391eb446f82c
Revises: 8f3deeb17ecc
Create Date: 2023-03-26 15:12:21.322470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391eb446f82c'
down_revision = '8f3deeb17ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_participant',
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sport_participant')
    # ### end Alembic commands ###
