"""added relationships

Revision ID: 77b4334dd7c1
Revises: 79dfbabb58e1
Create Date: 2023-03-22 21:40:23.168927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b4334dd7c1'
down_revision = '79dfbabb58e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_participant',
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('coach_id', 'participant_id')
    )
    op.create_table('sport_participant',
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('sport_id', 'participant_id')
    )
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('admin', 'trainer', 'user', name='usertypes'), nullable=True))

    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.drop_column('current_participants')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_participants', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_column('role')

    op.drop_table('sport_participant')
    op.drop_table('coach_participant')
    # ### end Alembic commands ###
