"""many to many coach&partcipant

Revision ID: 8f3deeb17ecc
Revises: c4a755b18fb7
Create Date: 2023-03-26 15:04:07.508676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3deeb17ecc'
down_revision = 'c4a755b18fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_coach',
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_coach')
    # ### end Alembic commands ###
