"""edited deliveed package model

Revision ID: a53a22eefd97
Revises: d0ad1fe20a76
Create Date: 2023-04-18 21:39:05.382890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53a22eefd97'
down_revision = 'd0ad1fe20a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivered_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_date', sa.DateTime(), nullable=False))
        batch_op.alter_column('delivered_by',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivered_packages', schema=None) as batch_op:
        batch_op.alter_column('delivered_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('delivered_date')

    # ### end Alembic commands ###
