"""one to many coach&sport

Revision ID: ac200b3b597c
Revises: 391eb446f82c
Create Date: 2023-03-26 15:25:01.939283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac200b3b597c'
down_revision = '391eb446f82c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sports', ['sport_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sport_id')

    # ### end Alembic commands ###
