"""active_subscriptions column added to allusers

Revision ID: c1f003acf586
Revises: a6377969e275
Create Date: 2023-04-12 22:39:14.469834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.ext.mutable import MutableList
# revision identifiers, used by Alembic.

revision = 'c1f003acf586'
down_revision = 'a6377969e275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_subscriptions', sa.ARRAY(sa.String), default=create_empty_list(), nullable=True))


    # ### end Alembic commands ###


def downgrade():

    op.create_table('registered_users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=15), nullable=False),
                    sa.Column('password', sa.String(length=220), nullable=False),
                    sa.Column('first_name', sa.String(length=15), nullable=False),
                    sa.Column('last_name', sa.String(length=15), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.Column('role', sa.Enum('admin', 'user', name='usertypes'), nullable=True),
                    sa.Column('verified', sa.Boolean, default=False, nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    # ### end Alembic commands ###
