"""edited onetimepayment model

Revision ID: cd71a2f7f144
Revises: 36e3b3ed9ac0
Create Date: 2023-04-16 15:49:09.703136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd71a2f7f144'
down_revision = '36e3b3ed9ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('one_time_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('one_time_payments', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###
