"""added verifed column in allusers

Revision ID: d322fe44d75b
Revises: ac200b3b597c
Create Date: 2023-03-28 22:20:41.103421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd322fe44d75b'
down_revision = 'ac200b3b597c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_users', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
