"""edited all models related to sports model, fixed relationships

Revision ID: ec78f0062240
Revises: 86808855b774
Create Date: 2023-04-14 21:36:28.826767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec78f0062240'
down_revision = '86808855b774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant_subscription',
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['active_subscriptions.id'], )
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_column('active_subscriptions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_subscriptions', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))

    op.drop_table('participant_subscription')
    op.drop_table('active_subscriptions')
    # ### end Alembic commands ###
